{% set name = "sphinx-needs" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_needs-{{ version }}.tar.gz
  sha256: b71ae36b3c14000ceedc42b1b230f214fececb227dbe4e282bc0b8ac7b7e76c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - poetry-core >=1.0.8
    - pip
  run:
    - python >=3.8.0
    - sphinx >=5.0,<8
    - requests-file >=1.5.1,<2.0.0
    - requests >=2.25.1,<3.0.0
    - jsonschema >=3.2.0
    - sphinxcontrib-plantuml
    - sphinx-data-viewer >=0.1.1,<0.2.0
    - matplotlib-base >=3.3.0

test:
  imports:
    - sphinx_needs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/useblocks/sphinx-needs
  summary: Sphinx needs extension for managing needs/requirements and specifications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
