{% set name = "sphinx-needs" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_needs-{{ version }}.tar.gz
  sha256: f1ae86afb3d1d3f3c5d8cecffe740ae03f32a908212b4471866dff1a0738b252

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - poetry-core >=1.0.8
    - pip
  run:
    - python >=3.8.0
    - sphinx >=6.0,<9
    - requests-file >=2.1.0,<3.0.0
    - requests >=2.32,<3.0.0
    - jsonschema >=3.2.0
    - sphinxcontrib-plantuml
    - sphinx-data-viewer >=0.1.5,<0.2.0
    - sphinxcontrib-jquery >=4,<5
    - matplotlib-base >=3.3.0

test:
  imports:
    - sphinx_needs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/useblocks/sphinx-needs
  summary: Sphinx needs extension for managing needs/requirements and specifications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
