context:
  name: sphinx-needs
  version: "7.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sphinx_needs-${{ version }}.tar.gz
  sha256: 3fa665181c323d0b76f6de0d8565f925f36933e8af4c253d34127755eff07371

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=${{ python_min }}
    - sphinx >=7.4,<10
    - requests-file >=2.1.0,<3.0.0
    - requests >=2.32,<3.0.0
    - jsonschema-rs >=0.37.1,<0.38
    - sphinx-data-viewer >=0.1.5,<0.2.0
    - sphinxcontrib-jquery >=4.0
    - tomli
    - typing-extensions >=4.14.0
    - minijinja >=2.15

tests:
  - python:
      imports:
        - sphinx_needs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Sphinx needs extension for managing needs/requirements and specifications
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/useblocks/sphinx-needs

extra:
  recipe-maintainers:
    - melund
