context:
  name: sphinx-needs
  version: "6.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sphinx_needs-${{ version }}.tar.gz
  sha256: 83a65f6ca4daf04efbf541dbbbe9830c9ee27cd00b24b57c1347f267cb290c55

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
    - pip
  run:
    - python
    - sphinx >=7.4,<9
    - requests-file >=2.1.0,<3.0.0
    - requests >=2.32,<3.0.0
    - jsonschema >=3.2.0
    # dependencies from jsonschema[format]
    - fqdn
    - idna
    - isoduration
    - jsonpointer >=1.13
    - rfc3339-validator
    - rfc3987
    - uri-template
    - webcolors >=1.11
    ###
    - sphinx-data-viewer >=0.1.5,<0.2.0
    - sphinxcontrib-jquery >=4,<5
    - if: match(python, "<3.11")
      then: tomli
    - typing-extensions >=4.14.0
    - typeguard >=4.4.4

tests:
  - python:
      imports:
        - sphinx_needs
  - requirements:
      run:
        - python
        - pip
    script:
      - pip check

about:
  summary: Sphinx needs extension for managing needs/requirements and specifications
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/useblocks/sphinx-needs

extra:
  recipe-maintainers:
    - melund
