context:
  name: sphinx-needs
  version: "5.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sphinx_needs-${{ version }}.tar.gz
  sha256: 61b07e7a4efcd0d5246ed8dab699d8fe3bc794331be63ac3afa94edfcfff7572

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=${{ python_min }}
    - sphinx >=7.0,<9
    - requests-file >=2.1.0,<3.0.0
    - requests >=2.32,<3.0.0
    - jsonschema >=3.2.0
    - sphinxcontrib-plantuml
    - sphinx-data-viewer >=0.1.5,<0.2.0
    - sphinxcontrib-jquery >=4,<5
    - matplotlib-base >=3.3.0

tests:
  - python:
      imports:
        - sphinx_needs
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Sphinx needs extension for managing needs/requirements and specifications
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/useblocks/sphinx-needs

extra:
  recipe-maintainers:
    - melund
